### ISSUE TITLE
Some functions do not work

### ISSUE THREAD

**Issue by JeffBeltran** [santigarcor/vscode-phpunit-extended#1]
Running version 1.0.3 on Mac (laravel 5.4 default test setup, if that matters)

Here is an example of the code im running the plugin with

```
class ListAllJobsTest extends TestCase
{
    use DatabaseMigrations, WithoutMiddleware;

    /** @test */
    function get_list_of_all_jobs()
    {
        $this->disableExceptionHandling();

        $employees = factory(Job::class, 5)->create();

        $response = $this->json('GET', '/api/jobs');

        $response->assertStatus(200);

        $this->assertEquals(5, count($response->json()));
    }
}
```

1) TestNearest doesn't run at all and i get no errors or feedback
2) Test only gives me option to run the Class but not any of the functions
3) All other functions of the plugin work (full suite, test file, run last)

I'll be happy to provide anything else for you and thanks again for making this, as it's one package i miss from sublime (https://packagecontrol.io/packages/phpunitkit)

**Comment by santigarcor** [comment]
I think the problem is that you're using `function get_list_of_all_jobs()` but the regex searching the functions looks for `public function get_list_of_all_jobs()`. You can check the regex right [here](https://github.com/santigarcor/vscode-phpunit-extended/blob/master/src/Helper.ts#L3)

Did you tried addind the `public`?

**Comment by JeffBeltran** [comment]
well that's an embarrassing oversight on my part...thats for pointing that out...So i take this back and i'll close out the issue.

Thanks again for the package

**Comment by santigarcor** [comment]
No problem man, but I'll try to change the regex so it accepts the methods without the public
