### ISSUE TITLE
Colors do not work

### ISSUE THREAD

**Issue by Talinon** [santigarcor/vscode-phpunit-extended#2]
Great plugin.. just one minor issue I'm having running on Linux Ubuntu 16.04

Output channel 'phpunit' has no red/green result color.
If I try adding the colors command line option, color codes are visible in the output window.

```
    "phpunit.args": [
        "--configuration", "./phpunit.xml",
        "--colors=always"
    ],

Result:
[30;42mOK (1 test, 4 assertions)
```

**Comment by santigarcor** [comment]
Can you please give me more information about the case so i try to replicate it, because i use it in Ubuntu 16.04 and it works fine.

**Comment by Talinon** [comment]
Since it worked for you, it got me thinking it was something to do with my configuration - which turns out it was. A color theme extension I was using (Slime) was causing the issue. When I switched back to a native theme the problem was resolved.

Sorry about that.. thanks for the quick response.
