### ISSUE TITLE
Request: exclude group

### ISSUE THREAD

**Issue by JeffBeltran** [santigarcor/vscode-phpunit-extended#4]
Hey it's me again 😄 
  
As for the request, I have some tests that i want to exclude from running as they talk to an outside API and thus make my test suite run SLOWWWWW. So I really only need to run the tests on my deployments or when i'm working on tests with that api. so to do this you would set the comment either on the class or test you want to exclude

```
/**
 * @group somegroup 
 */
```

and then call phpunit via `phpunit --exclude-group somegroup` 

I can do that right now by added that to the `phpunit.args` and it works. However, it is applied to all tests run with this extension and thus i can never run the excluded tests inside VSCODE (since PHPunit will ignore them)

So I would just submit a pull request but i suspect you'll have an easier time with it since i would have to research vscode extensions and typescript. However, looking at the codebase i think the simplest way to do this would be to create a new new setting `phpunit.excludedGroups` that takes an array of group names and when the `TestSuite` handler gets called checks if that array is set and if so runs the command with` --exclude-group somegroupname,anothergroupname`. Also if you really wanted to make things amazing you could add a new Handler `TestSuiteWithExcluded` that then ignores the excluded groups setting... much like the current `TestSuite` one works now.

Hopefully that made sense... Thanks in advance

**Comment by santigarcor** [comment]
I think it's doable. So the idea is that every time you run the command it asks you for the groups to ignore?

**Comment by JeffBeltran** [comment]
kinda, in short i would do these 2 things

1. Add a setting (`phpunit.excludedGroups`) that can be set by the user (an array of names would make the most sense)
2.  Create a new handler that is a copy of `TestSuite` but will append `--exclude-group somegroupname` to the command based on the `excludedGroups` setting

If you make it ask for groups to ignore every time it would get annoying IMO and would just be easier to run tests from terminal

**Comment by santigarcor** [comment]
Yeah, that's a better approach.

**Comment by santigarcor** [comment]
Added this in 1.0.5

**Comment by JeffBeltran** [comment]
Just tested and this works exactly how i would like it too, thanks mate!
