### ISSUE TITLE
Weird issue on running single tests

### ISSUE THREAD

**Issue by JeffBeltran** [santigarcor/vscode-phpunit-extended#5]
If i try to run a single test it will actually run tests that match similar names... for example

if i run the test 

`public function get_list_of_all_employees()`

it will also run 

`public function get_list_of_all_employees_listed_as_a_manager()`
`public function get_list_of_all_employees_listed_as_an_instructor()`

This happens on the `Test Nearest` as well as `Test` where I select the function name from the list

This really isn't a big deal, just a tad annoying and figured i would at least report it to you

Thanks again for the extension, it's one of my favorites

**Comment by santigarcor** [comment]
It's the expected behavior of phpunit, the plugin is running in this case `phpunit --filter=get_list_of_all_employees`, so it's going to run all tests with similar name in the current file.

**Comment by JeffBeltran** [comment]
did not know that, very interesting. Guess i'll just need to work on my method names to avoid this in the future. Anywhos thanks for the response
